### ISSUE TITLE
영화 API

### ISSUE THREAD

**Issue by piczza** [CinEffi/backend#12]
## 내용
* 적용 페이지 : 메인 페이지, 영화 검색 페이지
* 기능 : 영화 검색 기능

## TODO
- [x] 장르 데이터를 ENUM값으로 변경
- [x] 영화 검색 조회 API
- [x] 영화 개봉예정작 조회 API
- [x] 영화 랜덤 장르 조회 API
- [x] 일간박스오피스 영화 목록 조회 API
- [x] 영화 상세페이지 조회
- [x] 영화 스크랩(좋아요)
- [x] 영화 스크랩 취소
