### ISSUE TITLE
movie init의 병렬처리 로직 수정

### ISSUE THREAD

**Issue by piczza** [CinEffi/backend#164]
## 내용
영화 init 로직 수정

## TODO
- [x] 불필요 로직 제거
- [x] 코비스 키 자동 전환
- [x] 일부 필드 타입 변경
