### ISSUE TITLE
refactor/ 더미데이터 추가

### ISSUE THREAD

**Issue by piczza** [CinEffi/backend#65]
## 내용
* 적용 페이지 : 
* 기능 : 대부분의 기능

## TODO
- [x] 이미개봉 영화  30개 추가
- [x] 개봉예정 영화  20개 추가
- [x] 유저 50개 추가
- [x] 영화 평론 50개 추가
