### ISSUE TITLE
채팅 기능 구현

### ISSUE THREAD

**Issue by probablecode** [CinEffi/backend#7]
## 내용
* 적용 페이지 : 채팅 관련 페이지 모두
* 기능 : 채팅 기능

여러번의 PR 혹은 rebase를 거쳐서 완성될 것으로 예상됩니다.

## TODO
- [ ] 채팅 모듈 도입
  - [x] 웹소켓 연결
  - [x] 웹소켓 통신 
  - [ ] rdb 기반 기본 CRUD
    - [ ] search API 처리 (재욱님)
- [ ] postgreSQL 연동
